"""
AI-Generated Voice Detection API
Main FastAPI Application Entry Point
"""
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.exceptions import RequestValidationError
import time
import logging

from app.routes import router
from app.config import SUPPORTED_LANGUAGES

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Create FastAPI application
app = FastAPI(
    title="AI Voice Detection API",
    description="""
    ## AI-Generated Voice Detection API
    
    This API analyzes voice audio samples to detect whether they were generated by AI 
    or spoken by a real human.
    
    ### Supported Languages
    - Tamil
    - English
    - Hindi
    - Malayalam
    - Telugu
    
    ### Features
    - Base64 MP3 audio input
    - API key authentication
    - Confidence scoring
    - Detailed explanations
    
    ### Authentication
    All requests require a valid API key passed in the `x-api-key` header.
    """,
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_url="/openapi.json"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Request timing middleware
@app.middleware("http")
async def add_process_time_header(request: Request, call_next):
    """Add processing time to response headers"""
    start_time = time.time()
    response = await call_next(request)
    process_time = time.time() - start_time
    response.headers["X-Process-Time"] = str(round(process_time, 3))
    return response


# Exception handlers
@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    """Handle validation errors"""
    errors = exc.errors()
    error_messages = []
    for error in errors:
        field = ".".join(str(x) for x in error["loc"][1:])
        message = error["msg"]
        error_messages.append(f"{field}: {message}")
    
    return JSONResponse(
        status_code=400,
        content={
            "status": "error",
            "message": f"Validation error: {'; '.join(error_messages)}"
        }
    )


@app.exception_handler(Exception)
async def general_exception_handler(request: Request, exc: Exception):
    """Handle unexpected errors"""
    logger.error(f"Unexpected error: {str(exc)}", exc_info=True)
    return JSONResponse(
        status_code=500,
        content={
            "status": "error",
            "message": "An unexpected error occurred"
        }
    )


# Include routers
app.include_router(router, prefix="/api", tags=["Voice Detection"])


# Root endpoint
@app.get("/", tags=["Info"])
async def root():
    """Root endpoint with API information"""
    return {
        "service": "AI Voice Detection API",
        "version": "1.0.0",
        "description": "Detect AI-generated voices across multiple languages",
        "supported_languages": SUPPORTED_LANGUAGES,
        "endpoints": {
            "voice_detection": "/api/voice-detection",
            "health": "/api/health",
            "languages": "/api/languages",
            "docs": "/docs"
        }
    }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
