"""
API Routes for Voice Detection
"""
from fastapi import APIRouter, HTTPException, Header, Depends
from typing import Optional

from app.schemas import (
    VoiceDetectionRequest,
    VoiceDetectionResponse,
    ErrorResponse
)
from app.models.voice_detector import detect_voice
from app.config import API_KEYS

router = APIRouter()


async def verify_api_key(x_api_key: Optional[str] = Header(None, alias="x-api-key")) -> str:
    """
    Verify the API key from request headers
    
    Args:
        x_api_key: API key from x-api-key header
        
    Returns:
        The validated API key
        
    Raises:
        HTTPException: If API key is invalid or missing
    """
    if not x_api_key:
        raise HTTPException(
            status_code=401,
            detail={"status": "error", "message": "Missing API key. Include 'x-api-key' header."}
        )
    
    if x_api_key not in API_KEYS:
        raise HTTPException(
            status_code=401,
            detail={"status": "error", "message": "Invalid API key or malformed request"}
        )
    
    return x_api_key


@router.post(
    "/voice-detection",
    response_model=VoiceDetectionResponse,
    responses={
        200: {"model": VoiceDetectionResponse, "description": "Successful voice detection"},
        400: {"model": ErrorResponse, "description": "Bad request - invalid input"},
        401: {"model": ErrorResponse, "description": "Unauthorized - invalid or missing API key"},
        500: {"model": ErrorResponse, "description": "Internal server error"}
    },
    summary="Detect AI-generated voice",
    description="""
    Analyzes a voice audio sample to determine if it was generated by AI or spoken by a human.
    
    **Supported Languages:** Tamil, English, Hindi, Malayalam, Telugu, Bengali
    
    **Audio Requirements:**
    - Format: MP3
    - Encoding: Base64
    - One audio file per request
    
    **Authentication:**
    Requires a valid API key in the `x-api-key` header.
    """
)
async def detect_voice_endpoint(
    request: VoiceDetectionRequest,
    api_key: str = Depends(verify_api_key)
) -> VoiceDetectionResponse:
    """
    Endpoint to detect AI-generated voices
    
    Args:
        request: Voice detection request containing audio data
        api_key: Validated API key
        
    Returns:
        VoiceDetectionResponse with classification results
    """
    try:
        # Process the audio and get detection results
        result = detect_voice(
            audio_base64=request.audioBase64,
            audio_format=request.audioFormat,
            language=request.language
        )
        
        # Return the response
        return VoiceDetectionResponse(
            status="success",
            language=result["language"],
            classification=result["classification"],
            confidenceScore=result["confidence_score"],
            explanation=result["explanation"]
        )
        
    except ValueError as e:
        raise HTTPException(
            status_code=400,
            detail={"status": "error", "message": str(e)}
        )
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail={"status": "error", "message": f"Internal server error: {str(e)}"}
        )


@router.get(
    "/health",
    summary="Health check endpoint",
    description="Check if the API is running and healthy"
)
async def health_check():
    """Health check endpoint"""
    return {"status": "healthy", "service": "voice-detection-api"}


@router.get(
    "/languages",
    summary="Get supported languages",
    description="Returns the list of languages supported for voice detection"
)
async def get_supported_languages():
    """Get list of supported languages"""
    from app.config import SUPPORTED_LANGUAGES
    return {
        "status": "success",
        "languages": SUPPORTED_LANGUAGES
    }
